/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ChatMessage {
  'id' : bigint,
  'userEmail' : string,
  'adminReply' : [] | [string],
  'userId' : UserId,
  'repliedAt' : [] | [bigint],
  'message' : string,
  'timestamp' : bigint,
}
export type UserId = Principal;
export interface UserProfile {
  'id' : UserId,
  'displayName' : string,
  'email' : string,
  'registeredAt' : bigint,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'claimFirstAdmin' : ActorMethod<[], undefined>,
  'getAllChatMessages' : ActorMethod<[], Array<ChatMessage>>,
  'getAllUsers' : ActorMethod<[], Array<UserProfile>>,
  'getCallerUserProfile' : ActorMethod<[], UserProfile>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getChatMessagesForCaller' : ActorMethod<[], Array<ChatMessage>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'promoteToAdmin' : ActorMethod<[Principal], undefined>,
  'register' : ActorMethod<[string, string], undefined>,
  'replyToMessage' : ActorMethod<[bigint, string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'sendSupportMessage' : ActorMethod<[string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];